netty:
  # 服务器地址
  #host: 127.0.0.1
  #host: api.hadax.com
  host: api.hadax.com
  #api.huobi.pro
  # 端口号
  #port: 5544
  port: 80
  websocket:
    # 此处服务器的路径其实是 ws://127.0.0.1:9999/web_socket/${userName}
    url: ws
    user_name: tdg_yyx